### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by elgohr** [audi/fep3_sdk#1]
Sadly unusable due to missing license.

https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license

**Comment by PiJ82** [comment]
Hi @elgohr,

Unfortunately the license file in the root folder is missing. Thank you for pointing that out.

However, the license is located under doc/license. The entire code is distributed under the MPL2.0. This information is also part of the file header of every source file in this repository.

**Comment by elgohr** [comment]
For convenience (license scanners), it would be awesome if you could add it to the common paths.
